name: run-release-NO-race-condition

on:
  push:
    tags:
      - "NO-race-**"

permissions:
  contents: write
  id-token: write

jobs:
  run-release-NO-race-condition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - run: |
          echo "hello" > hello.txt
          echo "world" > world.txt

      - name: create-release-and-wait
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hello.txt
          draft: true
          token: ${{ secrets.ACTIONS_TOKEN  }}
          fail_on_unmatched_files: false

      - name: Sleep
        run: sleep 5

      - name: add-to-existing-release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            world.txt
          draft: true
          token: ${{ secrets.ACTIONS_TOKEN }}
          fail_on_unmatched_files: true
